// 5 theme presets inspired by reference designs
// All values map directly to CSS custom properties on :root

export const THEMES = {
  'warm-cafe': {
    id: 'warm-cafe',
    name: 'Warm Café',
    desc: 'Cozy amber & cream',
    dark: false,
    preview: { bg: '#faf7f3', accent: '#e8901f', surface: '#f3ede5', text: '#1a0f05' },
    vars: {
      '--color-bg':            '#faf7f3',
      '--color-surface':       '#f3ede5',
      '--color-card':          '#ffffff',
      '--color-card-hover':    '#fdf9f6',
      '--color-border':        '#e5d9cc',
      '--color-border-strong': '#cebdaa',
      '--color-accent':        '#c2700f',
      '--color-accent-dark':   '#a35c0a',
      '--color-accent-light':  '#e8901f',
      '--color-accent-bg':     '#fef3e2',
      '--color-accent-border': '#f9d89a',
      '--color-text':          '#1a0f05',
      '--color-text-secondary':'#4a3220',
      '--color-muted':         '#8c6a4e',
      '--color-muted-light':   '#b89880',
      '--glass-bg':            'rgba(255,255,255,0.88)',
      '--shimmer-from':        '#f0ebe5',
      '--shimmer-mid':         '#faf7f3',
      '--focus-ring':          'rgba(194,112,15,0.15)',
      '--card-shadow':         'rgba(100,60,20,0.10)',
      '--btn-shadow':          'rgba(194,112,15,0.35)',
    },
  },

  'midnight': {
    id: 'midnight',
    name: 'Midnight',
    desc: 'Bold dark elegance',
    dark: true,
    preview: { bg: '#111111', accent: '#f5c842', surface: '#1c1c1c', text: '#f0f0f0' },
    vars: {
      '--color-bg':            '#111111',
      '--color-surface':       '#1c1c1c',
      '--color-card':          '#1c1c1c',
      '--color-card-hover':    '#262626',
      '--color-border':        '#2e2e2e',
      '--color-border-strong': '#3a3a3a',
      '--color-accent':        '#d4a820',
      '--color-accent-dark':   '#a8850f',
      '--color-accent-light':  '#f5c842',
      '--color-accent-bg':     '#2a2200',
      '--color-accent-border': '#4a3c00',
      '--color-text':          '#f0f0f0',
      '--color-text-secondary':'#c8c8c8',
      '--color-muted':         '#888888',
      '--color-muted-light':   '#555555',
      '--glass-bg':            'rgba(20,20,20,0.92)',
      '--shimmer-from':        '#1a1a1a',
      '--shimmer-mid':         '#252525',
      '--focus-ring':          'rgba(245,200,66,0.20)',
      '--card-shadow':         'rgba(0,0,0,0.35)',
      '--btn-shadow':          'rgba(212,168,32,0.35)',
    },
  },

  'clean-pro': {
    id: 'clean-pro',
    name: 'Clean Pro',
    desc: 'Minimal & professional',
    dark: false,
    preview: { bg: '#f4f6f8', accent: '#2563eb', surface: '#eef1f5', text: '#111827' },
    vars: {
      '--color-bg':            '#f4f6f8',
      '--color-surface':       '#eef1f5',
      '--color-card':          '#ffffff',
      '--color-card-hover':    '#f8fafc',
      '--color-border':        '#e2e8f0',
      '--color-border-strong': '#cbd5e1',
      '--color-accent':        '#1d4ed8',
      '--color-accent-dark':   '#1e40af',
      '--color-accent-light':  '#3b82f6',
      '--color-accent-bg':     '#eff6ff',
      '--color-accent-border': '#bfdbfe',
      '--color-text':          '#111827',
      '--color-text-secondary':'#374151',
      '--color-muted':         '#6b7280',
      '--color-muted-light':   '#9ca3af',
      '--glass-bg':            'rgba(255,255,255,0.88)',
      '--shimmer-from':        '#e8edf2',
      '--shimmer-mid':         '#f4f6f8',
      '--focus-ring':          'rgba(37,99,235,0.15)',
      '--card-shadow':         'rgba(30,64,175,0.08)',
      '--btn-shadow':          'rgba(37,99,235,0.30)',
    },
  },

  'forest': {
    id: 'forest',
    name: 'Forest',
    desc: 'Fresh & natural',
    dark: false,
    preview: { bg: '#f0faf0', accent: '#16a34a', surface: '#e4f5e4', text: '#1a2e1a' },
    vars: {
      '--color-bg':            '#f0faf0',
      '--color-surface':       '#e4f5e4',
      '--color-card':          '#ffffff',
      '--color-card-hover':    '#f5fef5',
      '--color-border':        '#c6e6c6',
      '--color-border-strong': '#86c986',
      '--color-accent':        '#15803d',
      '--color-accent-dark':   '#14532d',
      '--color-accent-light':  '#22c55e',
      '--color-accent-bg':     '#f0fdf4',
      '--color-accent-border': '#bbf7d0',
      '--color-text':          '#1a2e1a',
      '--color-text-secondary':'#2d4a2d',
      '--color-muted':         '#4a7a4a',
      '--color-muted-light':   '#72a872',
      '--glass-bg':            'rgba(255,255,255,0.88)',
      '--shimmer-from':        '#e0f0e0',
      '--shimmer-mid':         '#f0faf0',
      '--focus-ring':          'rgba(21,128,61,0.15)',
      '--card-shadow':         'rgba(20,80,40,0.10)',
      '--btn-shadow':          'rgba(22,163,74,0.30)',
    },
  },

  'sweet-pink': {
    id: 'sweet-pink',
    name: 'Sweet Pink',
    desc: 'Playful & delightful',
    dark: false,
    preview: { bg: '#fff0f5', accent: '#e11d48', surface: '#fce7f3', text: '#1a0a0a' },
    vars: {
      '--color-bg':            '#fff0f5',
      '--color-surface':       '#fce7f3',
      '--color-card':          '#ffffff',
      '--color-card-hover':    '#fff8fb',
      '--color-border':        '#fbcfe8',
      '--color-border-strong': '#f9a8d4',
      '--color-accent':        '#be123c',
      '--color-accent-dark':   '#9f1239',
      '--color-accent-light':  '#e11d48',
      '--color-accent-bg':     '#fff1f2',
      '--color-accent-border': '#fecdd3',
      '--color-text':          '#1a0a0a',
      '--color-text-secondary':'#4a1020',
      '--color-muted':         '#9f3050',
      '--color-muted-light':   '#c47090',
      '--glass-bg':            'rgba(255,255,255,0.88)',
      '--shimmer-from':        '#fce7f3',
      '--shimmer-mid':         '#fff0f5',
      '--focus-ring':          'rgba(225,29,72,0.15)',
      '--card-shadow':         'rgba(159,18,57,0.10)',
      '--btn-shadow':          'rgba(225,29,72,0.30)',
    },
  },
};

export const THEME_IDS = Object.keys(THEMES);
export const DEFAULT_THEME = 'warm-cafe';

// Apply a full theme + optional custom overrides to :root
export function applyTheme(themeId, customColors = {}) {
  const base = THEMES[themeId]?.vars || THEMES[DEFAULT_THEME].vars;
  const merged = { ...base, ...customColors };
  const root = document.documentElement;
  Object.entries(merged).forEach(([k, v]) => root.style.setProperty(k, v));
  // Set dark-mode data attribute so CSS selectors can use it
  root.setAttribute('data-theme', THEMES[themeId]?.dark ? 'dark' : 'light');
}
